-- MySQL Script generated by MySQL Workbench
-- 02/14/20 15:26:29
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tcc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tcc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tcc` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `tcc` ;

-- -----------------------------------------------------
-- Table `tcc`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`login` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(100) NOT NULL COMMENT '',
  `sobrenome` VARCHAR(150) NOT NULL COMMENT '',
  `email` VARCHAR(100) NOT NULL COMMENT '',
  `senha` VARCHAR(100) NOT NULL COMMENT '',
  `ativo` CHAR(2) NULL COMMENT '',
  `forget` VARCHAR(150) NULL COMMENT '',
  `facebook_id` VARCHAR(45) NULL COMMENT '',
  `google_id` VARCHAR(45) NULL COMMENT '',
  `foto` VARCHAR(255) NULL COMMENT '',
  `created_at` TIMESTAMP NULL COMMENT '',
  `updated_at` TIMESTAMP NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc`.`motorista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`motorista` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `tipo_cnh` CHAR(4) NOT NULL COMMENT '',
  `cnh` VARCHAR(20) NOT NULL COMMENT '',
  `foto` VARCHAR(255) NOT NULL COMMENT '',
  `ativo` CHAR(2) NULL COMMENT '',
  `login_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_motorista_usuario1_idx` (`login_id` ASC)  COMMENT '',
  CONSTRAINT `fk_motorista_usuario1`
    FOREIGN KEY (`login_id`)
    REFERENCES `tcc`.`login` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc`.`rota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`rota` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `quantidade` INT(3) NOT NULL COMMENT '',
  `valor` DOUBLE NOT NULL COMMENT '',
  `cep_inicio` VARCHAR(15) NOT NULL COMMENT '',
  `cep_fim` VARCHAR(15) NOT NULL COMMENT '',
  `data_inicio` DATE NOT NULL COMMENT '',
  `cidade_inicio` VARCHAR(60) NOT NULL COMMENT '',
  `cidade_fim` VARCHAR(60) NOT NULL COMMENT '',
  `tamanho` CHAR(2) NOT NULL COMMENT '',
  `login_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_rota_usuario1_idx` (`login_id` ASC)  COMMENT '',
  CONSTRAINT `fk_rota_usuario1`
    FOREIGN KEY (`login_id`)
    REFERENCES `tcc`.`login` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`endereco` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `cep` VARCHAR(10) NOT NULL COMMENT '',
  `rua` VARCHAR(100) NOT NULL COMMENT '',
  `complemento` VARCHAR(100) NOT NULL COMMENT '',
  `bairro` VARCHAR(50) NOT NULL COMMENT '',
  `cidade` VARCHAR(70) NOT NULL COMMENT '',
  `estado` VARCHAR(45) NOT NULL COMMENT '',
  `numero` VARCHAR(10) NOT NULL COMMENT '',
  `usuario_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_endereco_usuario1_idx` (`usuario_id` ASC)  COMMENT '',
  CONSTRAINT `fk_endereco_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `tcc`.`login` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`venda` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `valor` DOUBLE NOT NULL COMMENT '',
  `date` DATE NOT NULL COMMENT '',
  `rota_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_item_rota1_idx` (`rota_id` ASC)  COMMENT '',
  CONSTRAINT `fk_item_rota1`
    FOREIGN KEY (`rota_id`)
    REFERENCES `tcc`.`rota` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc`.`pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`pagamento` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `tipo` VARCHAR(50) NOT NULL COMMENT '',
  `valor` DOUBLE NOT NULL COMMENT '',
  `data` DATE NOT NULL COMMENT '',
  `venda_id` INT NOT NULL COMMENT '',
  `login_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_pagamento_venda1_idx` (`venda_id` ASC)  COMMENT '',
  INDEX `fk_pagamento_usuario1_idx` (`login_id` ASC)  COMMENT '',
  CONSTRAINT `fk_pagamento_venda1`
    FOREIGN KEY (`venda_id`)
    REFERENCES `tcc`.`venda` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pagamento_usuario1`
    FOREIGN KEY (`login_id`)
    REFERENCES `tcc`.`login` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`produto` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(45) NOT NULL COMMENT '',
  `tamanho` CHAR(2) NOT NULL COMMENT '',
  `quantidade` INT NOT NULL COMMENT '',
  `login_id` INT NOT NULL COMMENT '',
  `item_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_produto_usuario1_idx` (`login_id` ASC)  COMMENT '',
  INDEX `fk_produto_item1_idx` (`item_id` ASC)  COMMENT '',
  CONSTRAINT `fk_produto_usuario1`
    FOREIGN KEY (`login_id`)
    REFERENCES `tcc`.`login` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_item1`
    FOREIGN KEY (`item_id`)
    REFERENCES `tcc`.`venda` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`status` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `tipo` CHAR(2) NOT NULL COMMENT '',
  `venda_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_status_venda1_idx` (`venda_id` ASC)  COMMENT '',
  CONSTRAINT `fk_status_venda1`
    FOREIGN KEY (`venda_id`)
    REFERENCES `tcc`.`venda` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc`.`cartao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`cartao` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nomeCartao` VARCHAR(150) NOT NULL COMMENT '',
  `mes` CHAR(2) NOT NULL COMMENT '',
  `ano` CHAR(4) NOT NULL COMMENT '',
  `numero` VARCHAR(20) NOT NULL COMMENT '',
  `codigo` CHAR(5) NOT NULL COMMENT '',
  `login_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_cartao_usuario1_idx` (`login_id` ASC)  COMMENT '',
  CONSTRAINT `fk_cartao_usuario1`
    FOREIGN KEY (`login_id`)
    REFERENCES `tcc`.`login` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc`.`comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`comentario` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `titulo` VARCHAR(80) NOT NULL COMMENT '',
  `texto` TEXT NOT NULL COMMENT '',
  `date` DATE NOT NULL COMMENT '',
  `login_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_comentario_usuario1_idx` (`login_id` ASC)  COMMENT '',
  CONSTRAINT `fk_comentario_usuario1`
    FOREIGN KEY (`login_id`)
    REFERENCES `tcc`.`login` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tcc`.`documentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`documentos` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `cpf` VARCHAR(15) NOT NULL COMMENT '',
  `rg` VARCHAR(15) NOT NULL COMMENT '',
  `date` DATE NOT NULL COMMENT '',
  `celular` VARCHAR(45) NOT NULL COMMENT '',
  `ativo` CHAR(2) NULL COMMENT '',
  `login_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_documentos_login1_idx` (`login_id` ASC)  COMMENT '',
  CONSTRAINT `fk_documentos_login1`
    FOREIGN KEY (`login_id`)
    REFERENCES `tcc`.`login` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
